#!/usr/bin/perl

$_=$ARGV[0];
$decode=&decode($_);
print "$decode\n";

# --------------------------------------------------------------------

sub decode {
    local($code)=@_;
    $tag=substr($code,0,3);
    $monat=substr($code,3,3);
    $jahr=substr($code,6,3);
    $_=substr($code,9,2);
#   print "$tag,$monat,$jahr,$_\n";

    #--- Datum
    $tag=($tag-113)/26;
    $monat=($monat-113)/73;
    $jahr=($jahr-113)/29+75;
    if ($jahr>100) {
	$jahr-=100;
    }
#    #--- Klasse
#    s/6.*/y/; s/7.*/z/;
#    s/51/xA/; s/52/xB/; s/53/xC/; s/54/xD/; s/55/xD/; s/56/xE/;
#    s/1(.+)/7$1/; s/2(.+)/8$1/; s/3(.+)/9$1/; s/4(.+)/10$1/; 
#    s/(.)1/$1K/; s/(.)2/$1M/; s/(.)3/$1NA/; 
#    s/(.)4/$1F1/; s/(.)5/$1F2/; s/(.)6/$1F3/; s/(.)7/$1F4/;
#    s/x/11/; s/y/12/; s/z/13/;
    #--- fertig
#    $tag.".".$monat.".".$jahr.",".$_;
    $tag.".".$monat.".".$jahr;
}

# --------------------------------------------------------------------
