#!/usr/bin/perl
# Zu allen Benutzern in /etc/passwd mit grp_id >= $grenze

$grenze=50;

# Korrekturen vornehmen

# von Eike Teiwes

print "------------------------------------------------------\n";
print "Korrekturen fuer alle Benutzer in /etc/passwd \n"; 

&durchlauf;

exit;

# --------------------------------------------------------------------

sub durchlauf {
    open (IN,"/etc/passwd");
    while (<IN>) {
	chop;
	($name,$x,$user,$group,$gcos)=split(/:/);
	($fullname)=split(/,/,$gcos);
	if ($group>=$grenze) {
	    print "        $name\n";
	    &anpassen;
	}    
    }
    close(IN);
}

# --------------------------------------------------------------------

sub anpassen1 {

    system("chown root /home/$name/system/netscape.ini");
    system("chgrp root /home/$name/system/netscape.ini");
    system("chmod a+rwx /home/$name/system/netscape.ini");
    system("chmod go-wx /home/$name/system/netscape.ini");

}

sub anpassen {

    #Netscape
    open(N_IN,"netscape.ini");
    open(N_OUT,">/home/$name/system/netscape.ini");
    while (<N_IN>) {
	if ($_ eq "") {
	    next;
	}
	if (/User_Addr=/) {
	    s/User_Addr=.*/User_Addr=$name\@ohg.goe.ni.schule.de\r/;
	}
	if (/User_Name=/) {
	    s/User_Name=.*/User_Name=$fullname\r/;
	}
	if (/POP Name=/) {
	    s/POP Name=.*/POP Name=$name\r/;
	}
	print N_OUT $_;
    }
    close(N_IN);
    close(N_OUT);

#    system("chown $name /home/$name/system/netscape.ini");
#    system("chgrp $group /home/$name/system/netscape.ini");
}

# --------------------------------------------------------------------

sub group {
    local($name)=@_;
    $_=`grep $name /etc/group`;
    /(\w+)\W+(\w+)\W+(\w+)/;
    $3;
}


 
















