#!/usr/bin/perl
# Benutzer aus /etc/passwd und /etc/shadow streichen und 
# Verzeichnise/Dateien löschen
# von Eike Teiwes

print "------------------------------------------------------\n";
print "Benutzer in /etc/passwd eintragen und Dateien kopieren\n"; 
$domain="ohg.goe.ni.schule.de";
$schueler=group("schueler");

&start_oder_stop;

print "    Abgänger austragen ($datdel >>> /etc/passwd .../shadow) und \n";
print "    Verzeichnisse/Dateien löschen\n";
&passwd_verkuerzen;
print "    --> $n Benutzer gestrichen\n";

exit;

# --------------------------------------------------------------------

sub start_oder_stop {
    @liste=`find datdel.* 2>/dev/null`;
    $i=0;
    print "    Vorhandene datdel.xxx sind:\n";
    foreach $_ (@liste) {
	++$i;
	print "        $_";
    }
    if ($i eq 0) {
	print "FEHLER: Datei datdel.xxx nicht gefunden.\n";
	print "Starten Sie zuvor das Programm listcmp.\n";
	exit;
    }
    if ($i>1) {
	print "    Welche Datei datdel.xxx soll benutzt werden?\n";
	print "        Index: ";
	$i=<STDIN>;
	$datdel=sprintf("datdel.%03d",$i);
    } else {
	$datdel=$liste[0];
	chop($datdel);
    }
    print "    ACHTUNG: Auch die Homeverzeichnisse werden gelöscht.\n";
    print "    Es kann sinnvoll sein, die Datei $datdel auzubewahren\n";
    print "    und die Benutzer erst später aus /etc/passwd zu streichen.\n";
    print "        Benutzer jetzt streichen? (j/n) ";
    $i=<STDIN>;
    chop($i);
    if (! ($i eq "j") && ! ($i eq "ja")) {
	print "abgebrochen\n";
	exit;
    }
}

# --------------------------------------------------------------------

sub passwd_verkuerzen {
    $n=0;
    open (IN,$datdel);
    while (<IN>) {
	chop;
	($name)=split(/:/);
	print("$name\n");
	++$n;
	system("userdel -r $name");
    }
    close(IN);
}

# --------------------------------------------------------------------

sub next_index {
    $_=sprintf("%03d",max_index(@_)+1);
    $_;
}

# --------------------------------------------------------------------

sub max_index {
    local($max)="000";
    foreach (`find @_ 2>/dev/null`) {
	$i=substr($_,-3,3);
	if ($i>$max) {
	    $max=$i;
	}
    }	
    $_=sprintf("%03d",$max);
    $_;
}

# --------------------------------------------------------------------

sub code {
    local($date)=@_;
    $date=substr($date,6,2).substr($date,3,2).substr($date,0,2);
    $date*937;
}

# --------------------------------------------------------------------

sub decode {
    local($code)=@_;
    $code=$code/937;
    substr($code,4,2).".".substr($code,2,2).".".substr($code,0,2);
}

# --------------------------------------------------------------------

sub group {
    local($name)=@_;
    $_=`grep $name /etc/group`;
    /(\w+)\W+(\w+)\W+(\w+)/;
    $3;
}











