#!/usr/bin/perl
# In der SHADOW-Datei das Ändern des Kennworts erlauben

# von Eike Teiwes

print "------------------------------------------------------\n";
print "SHADOW-Datei anpassen \n"; 

$index = next_index("/etc/shadow.*");
$datei = "shadow.$index";

print "Sicherheitskopie von shadow in $datei\n";

&durchfuehrung; # und Dateien kopieren und anpassen

exit;

# --------------------------------------------------------------------

sub durchfuehrung {
    system("cp /etc/shadow /etc/$datei");
    open (IN, "/etc/$datei");
    open (OUT, ">/etc/shadow");
    while (<IN>) {
	chop;
	($name, $passwd, $a, $b) = split(/:/);
	if ($b eq 0) {
	    print OUT "$_\n";
	} else {    
	    print OUT "$name:$passwd:$a\:0\:$b\:\:\:\:\n";
	}    
    }
    close(OUT);
    close(IN);
}
 
 
# --------------------------------------------------------------------

sub next_index {
    $_ = sprintf("%03d", max_index(@_)+1);
    $_;
}

# --------------------------------------------------------------------

sub max_index {
    local($max) = "000";
    foreach (`find @_ 2>/dev/null`) {
	$i = substr($_,-3,3);
	if ($i > $max) {
	    $max = $i;
	}
    }	
    $_ = sprintf("%03d", $max);
    $_;
}

# --------------------------------------------------------------------

#
# end shadow
