#!/usr/bin/perl
# In der SHADOW-Datei das Ändern des Kennworts erlauben
# von Eike Teiwes 18.09.98

$passwdFile = "/etc/passwd";
$shadowFile = "/etc/shadow";

print "\n";
print "            ------------------------------------------------------\n";
print "                           SHADOW-Datei anpassen \n"; 
print "            ------------------------------------------------------\n";
print "\n";

&vorbereitung;
&passwd_auslesen;
&doit; 

# --------------------------------------------------------------------

sub vorbereitung {
    $index=next_index("$passwdFile.???");
    $index2=next_index("$shadowFile.???");
    if ($index2>$index) {
	$index=$index2;
    }
    $shadowFile0=$shadowFile."\.".$index;
    system("cp -f $shadowFile $shadowFile0");
    print "Die Datei '$shadowFile' wurde als '$shadowFile0' gesichert.\n\n";
}

# --------------------------------------------------------------------

sub passwd_auslesen {
    $i=0;
    open (PWD,"$passwdFile");
    while (<PWD>) {
	chop;
        ($name,$passwd,$uid,$gid,$gcos)=split(/:/);
#	($fullname,$code)=split(/,/,$gcos);
	if (substr($name,0,1) eq "#") {
		$name=substr($name,1);	# gesperrter User
	}
	$feld{$name}="1";
        ++$i;
    }	
    close(PWD);
    print "$i Benutzer in '$passwdFile'\n";
}

# --------------------------------------------------------------------

sub doit {
    open (IN,"$shadowFile0");
    open (OUT,">$shadowFile");
    $m=0;
    $n=0;
    while (<IN>) {
	chop;
	++$m;
	($name,$passwd,$a,$b,$c)=split(/:/);
	if ($feld{$name} eq "1") {
		++$n;
		if ($c eq 10000) {
		    print OUT "$_\n";
		    print "\.";
		} else {    
		    print OUT "$name:$passwd:$a\:0\:10000\:\:\:\:\n";
		    print "+";
		}
	} else {
		print "-";
	}   
    }
    close(OUT);
    close(IN);
    print "\n";
    print "$m Benutzer in '$shadowFile'\.\n";
    print "$n davon bleiben erhalten.'\n";
}
 
# --------------------------------------------------------------------

sub next_index {
    $_=sprintf("%03d",max_index(@_)+1);
    $_;
}

# --------------------------------------------------------------------

sub max_index {
    local($max)="000";
    foreach (`find @_ 2>/dev/null`) {
	$i=substr($_,-3,3);
	if ($i>$max) {
	    $max=$i;
	}
    }	
    $_=sprintf("%03d",$max);
    $_;
}

# --------------------------------------------------------------------

