.TH "vitalnix" "7" "2009-09-04" "Vitalnix" "Vitalnix User Management Suite"
.SH "Name"
.PP
vitalnix \(em program suite for managing users
.SH "Manpage overview"
.PP
The documentation to Vitalnix is available in PDF format in your local
installation. Only program documentation is in manpage format.
.SS "Basic user/group information"
.PP
\fBvxid\fP(1) \(en print user identity
.PP
\fBvxfinger\fP(1) \(en user information lookup program
.SS "Shadow-style user/group administration"
.PP
\fBvxuseradd\fP(8) \(en create a new user
.PP
\fBvxusermod\fP(8) \(en modify a user acconut
.PP
\fBvxuserdel\fP(8) \(en delete a user account
.PP
\fBvxgroupadd\fP(8) \(en create a new group
.PP
\fBvxgroupmod\fP(8) \(en modify a group
.PP
\fBvxgroupdel\fP(8) \(en delete a group
.SS "User/group synchronization"
.PP
\fBvxckuuid\fP(8) \(en EDS UUID discrepancy checker
.PP
\fBvxfixuuid\fP(8) \(en VX3 UUID correction for users
.PP
\fBvxusersync\fP(8) \(en User account synchronization
.PP
\fBvxgroupbld\fP(8) \(en group membership synchronization
.PP
\fBvxpwlfmt\fP(8) \(en password list pretty-formatting
.PP
\fBvxnewuser\fP(8) \(en Single-user addition with handling for
Vitalnix-specific fields
.PP
\fBsteelmill\fP(8) \(en Graphical user interface for \fBvxusersync\fP(8)
.SS "Auxiliary tools and helpers"
.PP
\fBvxrandpw\fP(1) \(en generate random password
.PP
\fBvxdbdump\fP(8) \(en database dump program
.PP
\fBvxdbinfo\fP(8) \(en database module information program
.PP
\fBvxtryauth\fP(8) \(en command-line interface to authenticate with PAM
