#!/usr/bin/perl
# Verwalten von Benutzern mit Hilfe von Daten aus der Schulverwaltung
# von Eike Teiwes 20.03.97

print "----------------------------------------------------\n";
print "Benutzerverwaltung mit Hilfe von Schülerdaten\n";



&doit;

# --------------------------------------------------------------------

sub doit {
    $i=0;
    open (ZIEL,">p0");
    open (PWD,"p");
    while (<PWD>) {
	chop;
        ($name,$passwd,$uid,$gid,$gcos,$home,$shell)=split(/:/);
	print "$name\n";
$gcos=substr($gcos,0,-2);
	print ZIEL "$name:$passwd:$uid:$gid:$gcos:$home:$shell\n"; 
    }	
    close(PWD);
    close(ZIEL);
}

# --------------------------------------------------------------------

sub group {
    local($name)=@_;
    $_=`grep $name /etc/group`;
    /(\w+)\W+(\w+)\W+(\w+)/;
    $3;
}

