<?php include_once("Base-header.php"); ?>

<h1>Usage</h1>

<p class="code"><code>mdfixuuid -u <i>username</i> <b>[</b>-b <i>date</i><b>]</b>
<b>[</b>-r <i>name</i><b>]</b></code></p>

<h1>Options</h1>

<table border="1">
  <tr>
    <td class="t1">-b <i>date</i></td>
    <td class="t1">The new birthdate of the user</td>
  </tr>
  <tr>
    <td class="t2">-r <i>name</i></td>
    <td class="t2">The new realname of the user</td>
  </tr>
  <tr>
    <td class="t1">-u <i>user</i></td>
    <td class="t1">The user to modify</td>
  </tr>
</table>

<h1>Description</h1>

<p class="block">The <i>mdfixuuid</i> utility is used to regenerate the
Vitalnix UUID of a user when the data that was used to generate the UUID has
changed, mostly due to typographic fixes. If the UUID was not corrected by the
time the user database is synchronized again to the External Data Source, the
user will probably be deleted and instantly be readded with a new username.</p>

<p class="block">In Vitalnix 3, the UUID is generated from the birthdate and
the real name, so if either change upstream, the UUID needs to be adjusted.</p>

<p class="block">All of this only applies if the UUID is generated by Vitalnix;
if the External Data Source <i>does</i> already provide a UUID, then there is
no problem.</p>

<?php include_once("Base-footer.php"); ?>
