<?php include_once("Base-header.php"); ?>

<h1>Synopsis</h1>

<p class="code"><tt>vxcl_mdpwlfmt <b>[</b>-w<b>]</b> <b>[</b>-i
<i>file</i><b>]</b> <b>[</b>-o <i>file</i><b>]</b> <b>[</b>-s
<i>name</i><b>]</b> <b>[</b>-t <i>file</i><b>]</b></tt></p>

<h1>Options</h1>

<table border="1" class="bordered">
  <tr>
    <td class="t1">-i <i>file</i></td>
    <td class="t1">Input file, as generated by <i>libvxmdsync</i></td>
  </tr>
  <tr>
    <td class="t2">-o <i>file</i></td>
    <td class="t2">Place output in <i>file</i></td>
  </tr>
  <tr>
    <td class="t1">-s <i>name</i></td>
    <td class="t1">Use the specified style when converting the logfile to
      "readable" output</td>
  </tr>
  <tr>
    <td class="t2">-w</td>
    <td class="t2">Instead of converting, show all available styles</td>
  </tr>
</table>

<h1>Description</h1>

<?php include_once("Base-footer.php"); ?>
