#!/usr/bin/perl
#==============================================================================
# Vitalnix User Management Suite
#   Copyright © Jan Engelhardt <jengelh [at] linux01 gwdg de>, 2003 - 2005
#   -- License restrictions apply (LGPL v2.1)
#
#   This file is part of Vitalnix.
#   Vitalnix is free software; you can redistribute it and/or modify it
#   under the terms of the GNU Lesser General Public License as published
#   by the Free Software Foundation; however ONLY version 2 of the License.
#
#   Vitalnix is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public
#   License along with this program kit; if not, write to:
#   Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
#   Boston, MA  02110-1301  USA
#
#   -- For details, see the file named "LICENSE.LGPL2"
#==============================================================================
#
# Syntax: mkgroupdir [-b BASE] groupname
#
# Creates $BASE/g/gr/groupname
#
#------------------------------------------------------------------------------

## Hardcoded defaults
$base = "/home/groups";

## Code
use Getopt::Long;
&Getopt::Long::Configure(qw(bundling pass_through));
&GetOptions("b=s" => \$base);

$group = shift @ARGV;
if(length($group) < 3) { exit 1; }

$dir = sprintf "%s/%s/%s/%s", $base, substr($group, 0, 1),
 substr($group, 0, 2), $group;
&mkdir_p($dir) || die "Could not create $dir: $!\n";

#------------------------------------------------------------------------------
sub mkdir_p {
    my $fullpath = shift @_;
    my @list;

    $fullpath =~ s/\/$//so;
    @list = split(/\//so, $fullpath);

    for(my $i = 0; $i < scalar(@list); ++$i) {
        my $dir = join("/", @list[0..$i]);
        if(!-e $dir && !mkdir($dir)) { return 0; }
    }

    return 1;
}

#==============================================================================
